In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import matthews_corrcoef
from imblearn.metrics import geometric_mean_score
from imblearn.over_sampling import SMOTE

# Read the dataset

In [3]:
data_df = pd.read_csv('Dataset-vf.csv')
display(data_df.head())


X1     X2  X3   X4  X5    X6   X7   X8   X9   X10   X11  X12    X13  \
0  2709   59.0  11  120  43   150  228  217  120  2114  0.66  269   FC11   
1  2802   54.0   7    0   0   693  224  225  136   162  0.35  195   FC11   
2  2325   28.0  12    0   0  1260  215  213  133   162  0.89  750   FC14   
3  2837  112.0   8  272  16  3649  235  231  128  6221  0.27 -155   FC11   
4  2509   59.0   7  134  10   900  226  226  134  5184  0.93   88   FC11   

     X14  X15       Y  
0   CA49   R1   Melon  
1   CA50  NaN   Melon  
2   CA26  NaN  Carrot  
3   CA32  NaN  Orange  
4   CA38  NaN   Melon

In [4]:
print(data_df.corr())

           X1        X2        X3        X4        X5        X6        X7  \
X1   1.000000  0.002910 -0.333203  0.329017 -0.002311  0.606769  0.072518   
X2   0.002910  1.000000 -0.000115  0.019119  0.015753  0.075033 -0.591731   
X3  -0.333203 -0.000115  1.000000  0.018341  0.363640 -0.327663 -0.134366   
X4   0.329017  0.019119  0.018341  1.000000  0.624466  0.130159 -0.019646   
X5  -0.002311  0.015753  0.363640  0.624466  1.000000 -0.113061 -0.050173   
X6   0.606769  0.075033 -0.327663  0.130159 -0.113061  1.000000 -0.024238   
X7   0.072518 -0.591731 -0.134366 -0.019646 -0.050173 -0.024238  1.000000   
X8   0.229464  0.335285 -0.656795  0.047840 -0.213299  0.267689 -0.039172   
X9   0.122600  0.624552 -0.401927  0.038178 -0.131816  0.211251 -0.776999   
X10  0.463866 -0.053026 -0.235959  0.115299 -0.089477  0.445928  0.064237   
X11  0.001618 -0.028583  0.010468 -0.005063 -0.004616 -0.002762  0.011532   
X12 -0.002352 -0.012410  0.005183 -0.004866 -0.009564 -0.005791  0.016630   

<ipython-input-4-73b4a91b0e8c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(data_df.corr())


In [5]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6374 entries, 0 to 6373
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X1      6374 non-null   int64  
 1   X2      5747 non-null   float64
 2   X3      6374 non-null   int64  
 3   X4      6374 non-null   int64  
 4   X5      6374 non-null   int64  
 5   X6      6374 non-null   int64  
 6   X7      6374 non-null   int64  
 7   X8      6374 non-null   int64  
 8   X9      6374 non-null   int64  
 9   X10     6374 non-null   int64  
 10  X11     6374 non-null   float64
 11  X12     6374 non-null   int64  
 12  X13     6374 non-null   object 
 13  X14     6374 non-null   object 
 14  X15     631 non-null    object 
 15  Y       6374 non-null   object 
dtypes: float64(2), int64(10), object(4)
memory usage: 796.9+ KB


In [6]:
data_df.drop("X15", axis = 1,inplace=True)

In [7]:
data_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6374 entries, 0 to 6373
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X1      6374 non-null   int64  
 1   X2      5747 non-null   float64
 2   X3      6374 non-null   int64  
 3   X4      6374 non-null   int64  
 4   X5      6374 non-null   int64  
 5   X6      6374 non-null   int64  
 6   X7      6374 non-null   int64  
 7   X8      6374 non-null   int64  
 8   X9      6374 non-null   int64  
 9   X10     6374 non-null   int64  
 10  X11     6374 non-null   float64
 11  X12     6374 non-null   int64  
 12  X13     6374 non-null   object 
 13  X14     6374 non-null   object 
 14  Y       6374 non-null   object 
dtypes: float64(2), int64(10), object(3)
memory usage: 747.1+ KB


In [ ]:
#data_df["X2"] = data_df["X2"].fillna(data_df["X2"].mean())

In [8]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6374 entries, 0 to 6373
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X1      6374 non-null   int64  
 1   X2      5747 non-null   float64
 2   X3      6374 non-null   int64  
 3   X4      6374 non-null   int64  
 4   X5      6374 non-null   int64  
 5   X6      6374 non-null   int64  
 6   X7      6374 non-null   int64  
 7   X8      6374 non-null   int64  
 8   X9      6374 non-null   int64  
 9   X10     6374 non-null   int64  
 10  X11     6374 non-null   float64
 11  X12     6374 non-null   int64  
 12  X13     6374 non-null   object 
 13  X14     6374 non-null   object 
 14  Y       6374 non-null   object 
dtypes: float64(2), int64(10), object(3)
memory usage: 747.1+ KB


# One hot encoding 

In [9]:
#Convert Y from words to numbers
le = LabelEncoder()
data_df['Y'] = le.fit_transform(data_df['Y'])
print(data_df.corr())

           X1        X2        X3        X4        X5        X6        X7  \
X1   1.000000  0.002910 -0.333203  0.329017 -0.002311  0.606769  0.072518   
X2   0.002910  1.000000 -0.000115  0.019119  0.015753  0.075033 -0.591731   
X3  -0.333203 -0.000115  1.000000  0.018341  0.363640 -0.327663 -0.134366   
X4   0.329017  0.019119  0.018341  1.000000  0.624466  0.130159 -0.019646   
X5  -0.002311  0.015753  0.363640  0.624466  1.000000 -0.113061 -0.050173   
X6   0.606769  0.075033 -0.327663  0.130159 -0.113061  1.000000 -0.024238   
X7   0.072518 -0.591731 -0.134366 -0.019646 -0.050173 -0.024238  1.000000   
X8   0.229464  0.335285 -0.656795  0.047840 -0.213299  0.267689 -0.039172   
X9   0.122600  0.624552 -0.401927  0.038178 -0.131816  0.211251 -0.776999   
X10  0.463866 -0.053026 -0.235959  0.115299 -0.089477  0.445928  0.064237   
X11  0.001618 -0.028583  0.010468 -0.005063 -0.004616 -0.002762  0.011532   
X12 -0.002352 -0.012410  0.005183 -0.004866 -0.009564 -0.005791  0.016630   

<ipython-input-9-d2e7f3274598>:3: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  print(data_df.corr())


In [10]:

#Generate more features from existing ones
X13 = pd.get_dummies(data_df['X13'], prefix='X13')
X14 = pd.get_dummies(data_df['X14'], prefix='X14')

data_df = data_df.drop('X13',axis = 1)
data_df = data_df.drop('X14',axis = 1)

data_df = data_df.join(X13)
data_df = data_df.join(X14)

last_column = data_df.pop("Y")
data_df.insert(48,"Y", last_column)
print(data_df)



        X1     X2  X3   X4   X5    X6   X7   X8   X9   X10  ...  X14_ CA50  \
0     2709   59.0  11  120   43   150  228  217  120  2114  ...          0   
1     2802   54.0   7    0    0   693  224  225  136   162  ...          1   
2     2325   28.0  12    0    0  1260  215  213  133   162  ...          0   
3     2837  112.0   8  272   16  3649  235  231  128  6221  ...          0   
4     2509   59.0   7  134   10   900  226  226  134  5184  ...          0   
...    ...    ...  ..  ...  ...   ...  ...  ...  ...   ...  ...        ...   
6369  3101   67.0   6  170    1   824  227  228  135  1657  ...          0   
6370  3050  139.0  13   30   -3  3127  240  235  123  5770  ...          0   
6371  2080  106.0  24   30   12   582  252  202   64   108  ...          0   
6372  3011  108.0  10  212   36  2912  237  229  122  6632  ...          0   
6373  1980    3.0  22  300  125   300  185  193  140   927  ...          0   

      X14_ CA51  X14_ CA52  X14_ CA53  X14_ CA54  X14_ CA55  X1

# Fill missing data

In [11]:
data_df = np.array(data_df)
data = data_df[:,:-1]
labels = data_df[:,-1:]

In [12]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer


In [13]:
X_train, X_test, y_train, y_test = train_test_split(data, labels, train_size=0.7, random_state=201827000, stratify=labels)
X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, train_size=0.5, random_state=201827000, stratify=y_test)


impute_it = IterativeImputer().fit(X_train)
X_train = impute_it.transform(X_train)
X_val = impute_it.transform(X_val)
X_test =impute_it.transform(X_test) 


print('X_data={}'.format(data.shape))
print('X_train={}, X_val={}, X_test={}'.format(X_train.shape, X_val.shape, X_test.shape))
print('y_train={}, y_val={}, y_test={}'.format(y_train.shape, y_val.shape, y_test.shape))
print()
print('number of classes is  = ',(len(np.unique(y_train))))
print ('No. of training samples: ' + str(X_train.shape[0]))
print ('Number of features per sample: ' + str(X_train.shape[1]))
print()
print('class % in y_train = {}'.format((np.unique(y_train, return_counts=True)[1]/y_train.shape[0]).round(2)))
print('class % in y_val   = {}'.format((np.unique(y_val, return_counts=True)[1]/y_val.shape[0]).round(2)))
print('class % in y_test  = {}'.format((np.unique(y_test, return_counts=True)[1]/y_test.shape[0]).round(2)))

X_data=(6374, 48)
X_train=(4461, 48), X_val=(957, 48), X_test=(956, 48)
y_train=(4461, 1), y_val=(957, 1), y_test=(956, 1)

number of classes is  =  7
No. of training samples: 4461
Number of features per sample: 48

class % in y_train = [0.2  0.2  0.25 0.04 0.25 0.02 0.05]
class % in y_val   = [0.2  0.2  0.25 0.04 0.25 0.02 0.05]
class % in y_test  = [0.2  0.2  0.25 0.04 0.25 0.02 0.05]


In [14]:
print(np.isnan(X_train).sum() / X_train.size)

0.0


# Future selection based on lasso

In [16]:
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel

lsvc = LinearSVC(C=0.01, penalty="l1", dual=False).fit(X_train, y_train.ravel())
model = SelectFromModel(lsvc, prefit=True)
X_new = model.transform(X_train)
X_new_val = model.transform(X_val)
X_new_test = model.transform(X_test)
print(X_new.shape)
print(X_new_val.shape)
print(X_new_test.shape)
print(y_test.shape)

(4461, 27)
(957, 27)
(956, 27)
(956, 1)


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


# Over sampling using smote

In [17]:
oversampling = SMOTE(sampling_strategy='auto')
X_train_over_sample,y_train_over_sample = oversampling.fit_resample(X_new,y_train)

print('raw_data={}'.format(data.shape))
print('X_train={}, X_val={}, X_test={}'.format(X_train_over_sample.shape, X_new_val.shape, X_new_test.shape))
print('y_train={}, y_val={}, y_test={}'.format(y_train_over_sample.shape, y_val.shape, y_test.shape))
print()
print('number of classes is  = ',(len(np.unique(y_train_over_sample))))
print ('No. of training samples: ' + str(X_train_over_sample.shape[0]))
print ('Number of features per sample: ' + str(X_train_over_sample.shape[1]))
print()
print('class % in y_train = {}'.format((np.unique(y_train_over_sample, return_counts=True)[1]/y_train_over_sample.shape[0]).round(2)))
print('class % in y_val = {}'.format((np.unique(y_val, return_counts=True)[1]/y_val.shape[0]).round(2)))
print('class % in y_test = {}'.format((np.unique(y_test, return_counts=True)[1]/y_test.shape[0]).round(2)))

raw_data=(6374, 48)
X_train=(7938, 27), X_val=(957, 27), X_test=(956, 27)
y_train=(7938,), y_val=(957, 1), y_test=(956, 1)

number of classes is  =  7
No. of training samples: 7938
Number of features per sample: 27

class % in y_train = [0.14 0.14 0.14 0.14 0.14 0.14 0.14]
class % in y_val = [0.2  0.2  0.25 0.04 0.25 0.02 0.05]
class % in y_test = [0.2  0.2  0.25 0.04 0.25 0.02 0.05]


# Scalling for all sets 

In [18]:
scaler = preprocessing.StandardScaler().fit(X_train_over_sample)
train_data = scaler.transform(X_train_over_sample)
val_data = scaler.transform(X_new_val)
test_data = scaler.transform(X_new_test)

# List of appropriate evaluation measures

Precision: It measures the proportion of positive predictions that are actually correct.

Recall: It measures the proportion of positive examples that were correctly identified.

F1 score: It is a balance between precision and recall.

AUC-ROC: It measures the ability of a classifier to distinguish between positive and negative examples.

I choose F1 because its best way to measure evaluation because combine recall and precision together  

# SVM classifier 

In [19]:
from sklearn.svm import SVC
from sklearn.metrics import f1_score

degrees_list = [1, 2, 3, 4,5,6,7,8,9,10]
best_degree = 1
best_acc = 0.0
Choice = 0
for degree_val in degrees_list:
    clf = SVC(kernel = 'poly', degree = degree_val, random_state = 777)
    clf.fit(train_data,y_train_over_sample)
    y_pred_on_train = clf.predict(train_data)
    train_acc = f1_score(y_true=y_train_over_sample, y_pred=y_pred_on_train,average = "weighted")
    
    y_pred_on_val = clf.predict(val_data)
    val_acc = f1_score(y_true=y_val, y_pred=y_pred_on_val,average = "weighted" )
    
    print("Setting degree={}, train_acc={:.2f}, val_acc={:.2f}".format(degree_val, train_acc, val_acc))
    if val_acc > best_acc:
        best_acc = val_acc
        best_degree = degree_val
        Choice = 1
print("Best setting for poly degree={}, val_acc={:.2f}".format(best_degree, best_acc))
print()    
clf = SVC(kernel = 'linear', random_state = 777)
clf.fit(train_data,y_train_over_sample)
y_pred_on_train = clf.predict(train_data)
train_acc = f1_score(y_true=y_train_over_sample, y_pred=y_pred_on_train, average = "weighted")

y_pred_on_val = clf.predict(val_data)
val_acc = f1_score(y_true=y_val, y_pred=y_pred_on_val, average = "weighted")

print("linear train_acc={:.2f}, val_acc={:.2f}".format( train_acc, val_acc))

if val_acc > best_acc:
        best_acc = val_acc
        Choice = 2 

clf = SVC(kernel = 'rbf', random_state = 777)
clf.fit(train_data,y_train_over_sample)
y_pred_on_train = clf.predict(train_data)
train_acc = f1_score(y_true=y_train_over_sample, y_pred=y_pred_on_train, average = "weighted")

y_pred_on_val = clf.predict(val_data)
val_acc = f1_score(y_true=y_val, y_pred=y_pred_on_val, average = "weighted")

print("rbf train_acc={:.2f}, val_acc={:.2f}".format( train_acc, val_acc))

if val_acc > best_acc:
        best_acc = val_acc
        Choice = 3

if Choice == 1:
    print("Best setting is poly degree={}, val_acc={:.2f}".format(best_degree, best_acc))
if Choice == 2:
    print("Best setting is linear val_acc={:.2f}".format(best_acc))
if Choice == 3:
    print("Best setting is rbf val_acc={:.2f}".format(best_acc))

Setting degree=1, train_acc=0.85, val_acc=0.82
Setting degree=2, train_acc=0.90, val_acc=0.87
Setting degree=3, train_acc=0.92, val_acc=0.88
Setting degree=4, train_acc=0.90, val_acc=0.84
Setting degree=5, train_acc=0.87, val_acc=0.82
Setting degree=6, train_acc=0.85, val_acc=0.77
Setting degree=7, train_acc=0.80, val_acc=0.78
Setting degree=8, train_acc=0.76, val_acc=0.78
Setting degree=9, train_acc=0.74, val_acc=0.75
Setting degree=10, train_acc=0.73, val_acc=0.74
Best setting for poly degree=3, val_acc=0.88

linear train_acc=0.87, val_acc=0.84
rbf train_acc=0.92, val_acc=0.89
Best setting is rbf val_acc=0.89


# Results on the test set

In [20]:
X_train_val_merge = np.vstack([train_data, val_data]) 
y_train_val_merge = np.vstack([y_train_over_sample.reshape(y_train_over_sample.shape[0],1), y_val.reshape(y_val.shape[0],1)]) 
clf = SVC(kernel = 'rbf', random_state = 777)
clf.fit(X_train_val_merge,y_train_val_merge.ravel())
y_pred_on_test = clf.predict(test_data)
test_acc = f1_score(y_true=y_test.ravel(), y_pred=y_pred_on_test.ravel(), average = "weighted")
print("Best setting rbf test_acc={:.2f}".format(test_acc))
test_acc_Macro = f1_score(y_true=y_test.ravel(), y_pred=y_pred_on_test.ravel(), average = "macro")
test_acc_MCC = matthews_corrcoef(y_true=y_test.ravel(), y_pred=y_pred_on_test.ravel())
test_acc_gmean = geometric_mean_score(y_true=y_test.ravel(), y_pred=y_pred_on_test.ravel())




matrix = confusion_matrix(y_test.ravel(), y_pred_on_test.ravel())
c1 =  classification_report(y_test.ravel(), y_pred_on_test.ravel())

       

print("the confusion matrix as shown\n", matrix)
print(c1)
print()
print("F1-Weighted = {:.2f}".format(test_acc))
print("F1-Macro = {:.2f}".format(test_acc_Macro))
print("MCC = {:.2f}".format(test_acc_MCC))
print("Gmean = {:.2f}".format(test_acc_gmean))

Best setting rbf test_acc=0.87
the confusion matrix as shown
 [[157   0   0   0  14   8  12]
 [  0 137  28   9  13   0   0]
 [  0  12 228   3   0   0   0]
 [  0   5   0  33   0   0   0]
 [  7   5   0   3 213   8   0]
 [  0   0   0   0   1  14   0]
 [  2   0   0   0   0   0  44]]
              precision    recall  f1-score   support

         0.0       0.95      0.82      0.88       191
         1.0       0.86      0.73      0.79       187
         2.0       0.89      0.94      0.91       243
         3.0       0.69      0.87      0.77        38
         4.0       0.88      0.90      0.89       236
         5.0       0.47      0.93      0.62        15
         6.0       0.79      0.96      0.86        46

    accuracy                           0.86       956
   macro avg       0.79      0.88      0.82       956
weighted avg       0.87      0.86      0.87       956


F1-Weighted = 0.87
F1-Macro = 0.82
MCC = 0.83
Gmean = 0.88


# DecisionTreeClassifier

In [21]:
from sklearn.tree import DecisionTreeClassifier
best_acc = 0
creation = ['gini', 'entropy', 'log_loss']
for max_depth in range (3,30):
    for min_samples_split in range (2,10):
        for min_samples_leaf in range (2,10):
            for creat in creation:
                clf = DecisionTreeClassifier(random_state=201827000 , max_depth = max_depth, min_samples_split =min_samples_split, min_samples_leaf =min_samples_leaf, criterion = creat)
                clf = clf.fit(train_data, y_train_over_sample)

                y_pred_on_train = clf.predict(train_data)
                train_acc = f1_score(y_true=y_train_over_sample, y_pred=y_pred_on_train, average = "weighted")

                y_pred_on_val = clf.predict(val_data)
                val_acc = f1_score(y_true=y_val, y_pred=y_pred_on_val, average = "weighted")

                if val_acc > best_acc:
                    best_acc = val_acc
                    best_sample_split = min_samples_split
                    best_sample_leaf = min_samples_leaf
                    best_creation = creat
                    best_depth = max_depth
print("Best setting min_samples_split={}, min_samples_leaf={}, creation={}, max_depth={}, val_acc={:.2f}".format(min_samples_split, min_samples_leaf,creat, best_depth, best_acc))

Best setting min_samples_split=9, min_samples_leaf=9, creation=log_loss, max_depth=16, val_acc=0.91


# Results on the test set

In [22]:
clf = DecisionTreeClassifier (random_state=201827000 , max_depth = best_depth, min_samples_split =best_sample_split, min_samples_leaf =best_sample_leaf, criterion = best_creation)
clf = clf.fit(X_train_val_merge,y_train_val_merge.ravel())

y_test = y_test.ravel()

y_pred_on_test = clf.predict(test_data).ravel()
test_acc = f1_score(y_true=y_test.ravel(), y_pred=y_pred_on_test, average = "weighted")
test_acc_Macro = f1_score(y_true=y_test, y_pred=y_pred_on_test, average = "macro")
test_acc_MCC = matthews_corrcoef(y_true=y_test, y_pred=y_pred_on_test)
test_acc_gmean = geometric_mean_score(y_true=y_test, y_pred=y_pred_on_test)



print("Best accuracy on test set is test_acc={:.2f}".format(test_acc))
print()
print("F1-Weighted = {:.2f}".format(test_acc))
print("F1-Macro = {:.2f}".format(test_acc_Macro))
print("MCC = {:.2f}".format(test_acc_MCC))
print("Gmean = {:.2f}".format(test_acc_gmean))



Best accuracy on test set is test_acc=0.89

F1-Weighted = 0.89
F1-Macro = 0.86
MCC = 0.86
Gmean = 0.85


# RandomForestClassifier

In [23]:
from sklearn.ensemble import RandomForestClassifier
best_acc = 0
creation = ['gini', 'entropy', 'log_loss']
for max_depth in range (3,5):
    for min_samples_split in range (2,10):
        for min_samples_leaf in range (2,10):
            for n_estimators in range (50,140,15):
                for creat in creation:
                    clf = RandomForestClassifier(random_state=201827000 ,n_estimators = n_estimators, max_depth = max_depth, min_samples_split =min_samples_split, min_samples_leaf =min_samples_leaf, criterion = creat)
                    clf = clf.fit(train_data, y_train_over_sample)

                    y_pred_on_train = clf.predict(train_data)
                    train_acc = f1_score(y_true=y_train_over_sample, y_pred=y_pred_on_train, average = "weighted")

                    y_pred_on_val = clf.predict(val_data)
                    val_acc = f1_score(y_true=y_val, y_pred=y_pred_on_val, average = "weighted")

                    if val_acc > best_acc:
                        best_acc = val_acc
                        best_sample_split = min_samples_split
                        best_sample_leaf = min_samples_leaf
                        best_creation = creat
                        best_depth = max_depth
                        best_n_estimators = n_estimators
print("Best setting n_estimators={}, min_samples_split={}, min_samples_leaf={}, creation={}, max_depth={}, val_acc={:.2f}".format(best_n_estimators, min_samples_split, min_samples_leaf,creat, best_depth, best_acc))

Best setting n_estimators=110, min_samples_split=9, min_samples_leaf=9, creation=log_loss, max_depth=4, val_acc=0.78


# Results on the test set

In [24]:
clf = RandomForestClassifier (random_state=201827000 , n_estimators = best_n_estimators, max_depth = best_depth, min_samples_split =best_sample_split, min_samples_leaf =best_sample_leaf, criterion = best_creation)
clf = clf.fit(X_train_val_merge,y_train_val_merge.ravel())

y_pred_on_test = clf.predict(test_data).ravel()
test_acc = f1_score(y_true=y_test, y_pred=y_pred_on_test, average = "weighted")
test_acc_Macro = f1_score(y_true=y_test, y_pred=y_pred_on_test, average = "macro")
test_acc_MCC = matthews_corrcoef(y_true=y_test, y_pred=y_pred_on_test)
test_acc_gmean = geometric_mean_score(y_true=y_test, y_pred=y_pred_on_test)

print("Best accuracy on test set is test_acc={:.2f}".format(test_acc))
print()
print("F1-Weighted = {:.2f}".format(test_acc))
print("F1-Macro = {:.2f}".format(test_acc_Macro))
print("MCC = {:.2f}".format(test_acc_MCC))
print("Gmean = {:.2f}".format(test_acc_gmean))

Best accuracy on test set is test_acc=0.76

F1-Weighted = 0.76
F1-Macro = 0.68
MCC = 0.72
Gmean = 0.71


# Extra work and trying

In [25]:
df = pd.read_csv('Dataset-vf.csv')
df['Y'] = le.fit_transform(df['Y'])
df = df.drop('X13',axis = 1)
df = df.drop('X14',axis = 1)
df = df.drop('X15',axis = 1)

df = df.join(X13)
df = df.join(X14)

last_column = df.pop("Y")
df.insert(48,"Y", last_column)
display(df)


X1     X2  X3   X4   X5    X6   X7   X8   X9   X10  ...  X14_ CA50  \
0     2709   59.0  11  120   43   150  228  217  120  2114  ...          0   
1     2802   54.0   7    0    0   693  224  225  136   162  ...          1   
2     2325   28.0  12    0    0  1260  215  213  133   162  ...          0   
3     2837  112.0   8  272   16  3649  235  231  128  6221  ...          0   
4     2509   59.0   7  134   10   900  226  226  134  5184  ...          0   
...    ...    ...  ..  ...  ...   ...  ...  ...  ...   ...  ...        ...   
6369  3101   67.0   6  170    1   824  227  228  135  1657  ...          0   
6370  3050  139.0  13   30   -3  3127  240  235  123  5770  ...          0   
6371  2080  106.0  24   30   12   582  252  202   64   108  ...          0   
6372  3011  108.0  10  212   36  2912  237  229  122  6632  ...          0   
6373  1980    3.0  22  300  125   300  185  193  140   927  ...          0   

      X14_ CA51  X14_ CA52  X14_ CA53  X14_ CA54  X14_ CA55  X14_ CA58  \
0             0          0          0          0          0          0   
1             0          0          0          0          0          0   
2             0          0          0          0          0          0   
3             0          0          0          0          0          0   
4             0          0          0          0          0          0   
...         ...        ...        ...        ...        ...        ...   
6369          0          0          0          0          0          0   
6370          0          0          0          0          0          0   
6371          0          0          0          0          0          0   
6372          0          0          0          0          0          0   
6373          0          0          0          0          0          0   

      X14_ CA59  X14_ CA60  Y  
0             0          0  4  
1             0          0  4  
2             0          0  2  
3             0          0  5  
4             0          0  4  
...         ...        ... ..  
6369          0          0  0  
6370          0          0  0  
6371          0          0  2  
6372          0          0  0  
6373          0          0  3  

[6374 rows x 49 columns]

In [26]:
int(len(df)*0.7)

4461

In [27]:
dummy_traindf = df.iloc[0:int(len(df)*0.7)]

In [28]:
#LinearRegression to fill mising values 

lr = LinearRegression()
testdf = dummy_traindf[dummy_traindf['X2'].isnull()==True]
traindf = dummy_traindf[dummy_traindf['X2'].isnull()==False]
y = traindf['X2']
traindf.drop("X2",axis=1,inplace=True)
lr.fit(traindf,y)
testdf.drop("X2",axis=1,inplace=True)
pred = lr.predict(testdf)
testdf['X2']= pred

<ipython-input-28-d535d432ca5f>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  traindf.drop("X2",axis=1,inplace=True)
<ipython-input-28-d535d432ca5f>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testdf.drop("X2",axis=1,inplace=True)
<ipython-input-28-d535d432ca5f>:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testdf['X2']= pred


In [29]:
traindf['X2']=y

<ipython-input-29-fefe37d846da>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  traindf['X2']=y


In [30]:
y = traindf['Y']
traindf.drop('Y',axis=1,inplace=True)
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(traindf,y)

<ipython-input-30-3940c41f423f>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  traindf.drop('Y',axis=1,inplace=True)
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [31]:
y_test_dummy = testdf['Y']
testdf.drop("Y",axis=1,inplace=True)
pred = lr.predict(testdf)

<ipython-input-31-b7310587343c>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testdf.drop("Y",axis=1,inplace=True)


In [32]:
print(metrics.accuracy_score(pred,y_test_dummy))

0.6426966292134831


# Error analysis and possible improvements

do more feature selection try different balancing techniques also maybe more tuning for hyperparametars